AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for OtterTune AWS Integration
Parameters:
  ExternalId:
    Description: >-
      External ID for the OtterTune role. Copy from OtterTune role setup wizard.
    Type: String
  IAMRoleName:
    Description: Customize the name of IAM role for OtterTune
    Type: String  
    Default: OtterTuneRole
  OtterTuneAWSAccountId:
    Description: >-
      OtterTune AWS account ID allowed to assume the IAM role. DO NOT CHANGE!
    Type: String
    Default: "691523222388"
  TunableParameterGroupArns:
    Description: >-
      Pass in the parameter group ARNs that you'd like to allow OtterTune to optimize. Separate groups by comma, (e.g., "<arn1>,<arn2>") 
      Leave blank if you would like to run OtterTune in monitoring-only mode for now. This can be updated later.
      ARN Format: arn:aws:rds:<region>:<account>:pg:<name>
    Type: CommaDelimitedList
    Default: ""
  TunableAuroraClusterParameterGroupArns:
    Description: >-
      Pass in the aurora cluster parameter group ARNs that you'd like to allow OtterTune to optimize. Separate groups by comma, (e.g., "<arn1>,<arn2>") 
      Leave blank if you would like to run OtterTune in monitoring-only mode for now. This can be updated later.
      ARN Format: arn:aws:rds:<region>:<account>:cluster-pg:<name>
    Type: CommaDelimitedList
    Default: ""

Conditions:
  HasParameterGroups: !Not
    - !Equals 
      - !Join 
        - ''
        - !Ref TunableParameterGroupArns
      -  ''
  HasClusterParameterGroups: !Not
    - !Equals 
      - !Join 
        - ''
        - !Ref TunableAuroraClusterParameterGroupArns
      -  ''
  CreateTuningPolicy: !Or
    - !Condition HasParameterGroups
    - !Condition HasClusterParameterGroups

Resources:
  OtterTuneRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${OtterTuneAWSAccountId}:root'
                - { OtterTuneAWSAccountId: !Ref OtterTuneAWSAccountId}
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      Path: /
      RoleName: !Ref IAMRoleName
      Policies:
        - PolicyName: OtterTuneDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Resource: '*'
              Action:
                - rds:Describe*
                - rds:List*
                - cloudwatch:Get*
                - cloudwatch:List*
                - ce:Get*
                - ce:List*
                - ce:Describe*
                - aws-portal:ViewBilling
                - iam:SimulatePrincipalPolicy
        - PolicyName: OtterTuneConnectPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Resource: arn:aws:rds-db:*:*:dbuser:*/ottertune*
              Action:
                - rds-db:connect
        - !If
          - CreateTuningPolicy
          - 
            PolicyName: !Sub
              - ${StackName}-ottertune-tuning-policy
              - { StackName: !Ref AWS::StackName }
            PolicyDocument:
              Version: 2012-10-17
              Statement:
              - !If
                - HasParameterGroups
                -
                  Effect: Allow
                  Resource: !Ref TunableParameterGroupArns
                  Action:
                    - rds:ModifyDBParameterGroup
                - !Ref AWS::NoValue
              - !If
                - HasClusterParameterGroups
                -
                  Effect: Allow
                  Resource: !Ref TunableAuroraClusterParameterGroupArns
                  Action:
                    - rds:ModifyDBClusterParameterGroup
                - !Ref AWS::NoValue
          - !Ref AWS::NoValue

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - ExternalId
        - IAMRoleName
    - Label:
        default: Optional
      Parameters:
        - TunableParameterGroupArns
        - TunableAuroraClusterParameterGroupArns
    - Label:
        default: Do not change
      Parameters:
        - OtterTuneAWSAccountId
